config/routes.rb
Treinolivre::Application.routes.draw do
  resources :kinds

  resources :courses do
    resources :lessons
  end

  resources :lessons do
    resources :activities
  end

  resources :notes

  resources :roles

  resources :companies

  devise_for :users
  resources :users

  get "pages/index"
  root :to => "pages#index"

  resources :categories
  match '/home'   => "pages#home",  :as => :home
  match '/contato'   => "pages#contato",  :as => :contato
  match '/metodo'   => "pages#metodo",  :as => :metodo
  match '/user' => "courses#index", :as => :user_root

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :company
  has_and_belongs_to_many :roles
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :company_id, :email, :password, :password_confirmation, :remember_me, :role_ids

  def role?(role)
   return !!self.roles.find_by_name(role) 
   #return !!self.roles.find_by_name(role.to_s.camelize) 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  layout "admin"

  # GET /users
  # GET /users.xml
  def index
#    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @current_method = "new"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @current_method = "edit"
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Nome Completo", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :email, :placeholder => "E-mail", :size => 50 %>
  </div>

  <% if can? :manage, :all %>
     <div class="field">
      <%= f.select :company_id, Company.find(:all).collect { |item| [item.name, item.id] } %>
    </div>
  <% else %>
     <div class="field">
      <%= f.hidden_field :company_id, :value => current_user.company.id %>
    </div>
  <% end %> 

  <% if @current_method == "new" %>
    <div class="field">
      <%= f.password_field :password, :placeholder => "Digite sua Senha", :size => 50 %>
    </div>
    <div class="field">
      <%= f.password_field :password_confirmation, :placeholder => "Confirme sua Senha", :size => 50 %>
    </div>
  <% end %>
  
  <% if @current_method == "edit" %>
    <% if @user.id == current_user.id or current_user.role? :Admin #if @current_method == "new" %>
      <div class="field">
        <%= f.password_field :password, :placeholder => "Digite sua Senha", :size => 50 %>
      </div>
      <div class="field">
        <%= f.password_field :password_confirmation, :placeholder => "Confirme sua Senha", :size => 50 %>
      </div>
    <% end %>
  <% end %>

  <% if current_user.role? :Admin %>
    <% for role in Role.find(:all) %>
      <div>
        <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
        <%= role.name %>
      </div>
    <% end %>
  <% end %>

  <% if current_user.role? :Gestor and @user.id == current_user.id %>
    <div>
      <%= check_box_tag "user[role_ids][]", "3", true %> Gestor<br />
    </div>
  <% else %>
    <% if current_user.role? :Gestor %>
        <%= check_box_tag "user[role_ids][]", "2" %> Aluno<br />
        <%= check_box_tag "user[role_ids][]", "4" %> Orientador
    <% end %>
  <% end %>

  <% if current_user.role? :Orientador and @user.id == current_user.id %>
    <div>
      <%= check_box_tag "user[role_ids][]", "4", true %> Orientador<br />
    </div>
  <% else %>
    <% if current_user.role? :Orientador %>
      <div>
        <%= check_box_tag "user[role_ids][]", "2", true %> Aluno<br />
      </div>
    <% end %>
  <% end %>
    
  <div class="actions">
    <br /><%= f.submit %>
  </div>

<% end %>

app/views/users/_user.html.erb
<h1 class="title-config"><%=t ".title" %> / <%= link_to t('.new'), new_user_path %></h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th colspan="2"></th>
  </tr>

  <% @users.each do |user| %>
    <tr class="<%= cycle("even", "odd") %>">
      <td><%= link_to user.email, user %></td>
      <td>
        <% for role in user.roles %>
          <%= role .name %>
        <% end %>
      </td>
      <td><%= user.company.name %></td>
      <td><%= link_to t(:edit), edit_user_path(user) %></td>
      <td><%= link_to t(:destroy), user, :confirm => t(:confirm), :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br />

app/views/users/edit.html.erb
<h1 class="title-form"><%=t ".title" %></h1>
<% if current_user.role? :Aluno %>
  <%= link_to(image_tag("voltar-24.png", :title => "Voltar"), courses_path, :class => "back-link") %><br /><br />
<% else %>
  <%= link_to(image_tag("voltar-24.png", :title => "Voltar"), users_path, :class => "back-link") %><br /><br />
<% end %>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="title-config"><%=t ".title" %> 
<% if can? :create, User %>
     / <%= link_to  new_user_path do %>
        <%= image_tag("novo-32.png", :title => "Criar Novo Usuário") %>
        <span class="text-link">Criar Novo Usuário</span>
      <% end %>
<% end %>
</h1>

<table cellspacing="0">
  <tr>
    <th></th>
    <th></th>
    <th colspan="2"></th>
  </tr>

    <% @users.each do |user| %>
    <tr class="<%= cycle("even", "odd") %>">
      <td><%= link_to user.email, user %></td>
      <td>
        <% if current_user.name == user.name %>
          <strong><%= user.name %></strong>
        <% else %>
          <%= user.name %>
        <% end %>
      </td>
      <td>
        <% for role in user.roles %>
          <%= role.name %>
        <% end %>
      </td>
      <td><%= user.company.name %></td>
      <% if can? :manage, User %>
      <td><%= link_to(image_tag("editar-24.png", :title => "Editar Usuário"), edit_user_path(user)) %></td>
        <td><%= link_to(image_tag("apagar-24.png", :title => "Excluir Usuário"), user, :confirm => t(:confirm), :method => :delete) %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br />

app/views/users/new.html.erb
<h1 class="title-form"><%=t ".title" %></h1>

<%= link_to(image_tag("voltar-24.png", :title => "Voltar"), users_path, :class => "back-link") %><br /><br />

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="logo-show">
  <%= image_tag avatar_url(@user) %>
</div>

<div class="name-show">
  <h1><%= @user.name %></h1><br />
    <% if current_user.role? :Aluno %>
      <%= link_to(image_tag("voltar-24.png", :title => "Voltar"), courses_path) %>  
    <% else %>
      <%= link_to(image_tag("voltar-24.png", :title => "Voltar"), users_path) %>  
    <% end %>
    <% if current_user.role? [:Admin, :Gestor] or @user.id == current_user.id %>
      <%= link_to(image_tag("editar-24.png", :title => "Editar"), edit_user_path) %>
    <% end %>

  <br /><p><%= @user.company.name %></p><br /><br />

</div>