config/routes.rb
Treinolivre::Application.routes.draw do
  resources :kinds

  resources :courses do
    resources :lessons
  end

  resources :lessons do
    resources :activities
  end

  resources :notes

  resources :roles

  resources :companies

  devise_for :users
  resources :users

  get "pages/index"
  root :to => "pages#index"

  resources :categories
  match '/home'   => "pages#home",  :as => :home
  match '/contato'   => "pages#contato",  :as => :contato
  match '/metodo'   => "pages#metodo",  :as => :metodo
  match '/user' => "courses#index", :as => :user_root

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
  has_many :notes
  has_attached_file :logo,
                          :styles => {
                            :small => "150x150>"
                          }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  layout "admin"
  # GET /companies
  # GET /companies.xml
  def index
#    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.xml
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.xml
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.xml
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
        format.xml  { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.xml
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to(@company, :notice => 'Company was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.xml
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, :html => { :multipart => true }) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Nome da Empresa", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :address, :placeholder => "Endereço Completo", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :city, :placeholder => "Cidade", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :state, :placeholder => "Estado", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :zipcode, :placeholder => "CEP", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :cnpj, :placeholder => "CNPJ", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :contractor, :placeholder => "Contratante", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :email, :placeholder => "E-mail", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :phone, :placeholder => "Telefone Fixo", :size => 50 %>
  </div>

  <div class="field">
    <%= f.text_field :cellphone, :placeholder => "Telefone Celular", :size => 50 %>
  </div>

  <div class="field">
    <%= f.file_field :logo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1 class="title-form"><%=t ".title" %></h1>

<% if current_user.role? :Gestor %>
  <%= link_to(image_tag("voltar-24.png", :title => "Voltar"), company_path(@company), :class => "back-link") %><br /><br />
<% else %>
  <%= link_to(image_tag("voltar-24.png", :title => "Voltar"), companies_path, :class => "back-link") %><br /><br />
<% end %>

<%= render 'form' %>

app/views/companies/index.html.erb
<h1 class="title-config"><%=t ".title" %>
  <% if can? :manage, :all %>
    / <%= link_to  new_company_path do %>
        <%= image_tag("novo-32.png", :title => "Criar Nova Empresa") %>
        <span class="text-link">Criar Nova Empresa</span>
      <% end %>
  <% end %>
</h1>

<table cellspacing="0">
  <tr>
    <th colspan="2"></th>
  </tr>

<% @companies.each do |company| %>
  <tr class="<%= cycle("even", "odd") %>">
    <td><%= link_to company.name, company %></td>
    <td><%= company.state %></td>
    <td><%= company.contractor %></td>
    <td><%= company.phone %></td>
      <td><%= link_to(image_tag("editar-24.png", :title => "Editar Empresa"), edit_company_path(company)) %></td>
    <% if can? :manage, :all %>
      <td><%= link_to(image_tag("apagar-24.png", :title => "Excluir Empresa"), company, :confirm => t(:confirm), :method => :delete) %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

app/views/companies/new.html.erb
<h1 class="title-form"><%=t ".title" %></h1>

<%= link_to(image_tag("voltar-24.png", :title => "Voltar"), companies_path, :class => "back-link") %><br /><br />

<%= render 'form' %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="logo-show">
  <%= image_tag @company.logo.url(:small) %>
</div>

<div class="name-show">
  <h1><%= @company.name %></h1><br />
  <% if current_user.role? :Gestor %>
  <%= link_to(image_tag("editar-24.png", :title => "Editar"), edit_company_path(@company)) %>
  <% else %>
  <%= link_to(image_tag("voltar-24.png", :title => "Voltar"), companies_path) %>  
  <%= link_to(image_tag("editar-24.png", :title => "Editar"), edit_company_path(@company)) %>
  <% end %>
</div>

<div class="content-show">

  <%= @company.address %>





  <table>
    <tr>
      <td class="td-title-company">Contractor</td><td><%= @company.contractor %></td>
    </tr>
      <td class="td-title-company">Address</td><td><%= @company.address %></td>
    </tr>
      <td class="td-title-company">City</td><td><%= @company.city %></td>
    </tr>
      <td class="td-title-company">State</td><td><%= @company.state %></td>
    </tr>
      <td class="td-title-company">Zipcode</td><td><%= @company.zipcode %></td>
    </tr>
      <td class="td-title-company">Cnpj</td><td><%= @company.cnpj %></td>
    </tr>
      <td class="td-title-company">Phone</td><td><%= @company.phone %></td>
    </tr>
      <td class="td-title-company">Cellphone</td><td><%= @company.cellphone %></td>
    </tr>
  </table>
</div>