config/routes.rb
Treinolivre::Application.routes.draw do
  resources :kinds

  resources :courses do
    resources :lessons
  end

  resources :lessons do
    resources :activities
  end

  resources :notes

  resources :roles

  resources :companies

  devise_for :users
  resources :users

  get "pages/index"
  root :to => "pages#index"

  resources :categories
  match '/home'   => "pages#home",  :as => :home
  match '/contato'   => "pages#contato",  :as => :contato
  match '/metodo'   => "pages#metodo",  :as => :metodo
  match '/user' => "courses#index", :as => :user_root

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :lesson
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.xml
  before_filter :load_lesson
  layout "classes", :except => [:edit]
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.xml
  def show
    @activity = @lesson.activities.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.xml
  def new
    @activity = @lesson.activities.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = @lesson.activities.find(params[:id])
    render :layout => "admin"
  end

  # POST /activities
  # POST /activities.xml
  def create
    @activity = @lesson.activities.build(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to([@lesson.course, @lesson], :notice => 'Activity was successfully created.') }
        format.xml  { render :xml => @activity, :status => :created, :location => @activity }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.xml
  def update
    @activity = @lesson.activities.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to([@lesson.course, @lesson], :notice => 'Activity was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.xml
  def destroy
    @activity = @lesson.activities.find(params[:id])
    @activity.destroy

    respond_to do |format|
      #format.html { redirect_to(activities_url) }
      format.html { redirect_to([@lesson.course, @lesson]) }
      format.xml  { head :ok }
    end
  end

  def load_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
  <tr class="<%= cycle("even", "odd") %>" >
    <td><%= link_to activity.name, lesson_activity_path(@lesson, activity), :target => "_blank" %></td>
  <% if can? :manage, :all %>
    <td><%= link_to(image_tag("editar-24.png", :title => "Editar"), edit_lesson_activity_path(@lesson, activity)) %></td>
    <td><%= link_to(image_tag("apagar-24.png", :title => "Apagar"), [activity.lesson, activity], :confirm => t(:confirm), :method => :delete) %></td>
  <% end %>
  </tr>

app/views/activities/_form.html.erb
<%= form_for([lesson, activity]) do |f| %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Tema da Atividae", :size => 50 %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/activities/edit.html.erb
<h1 class="title-form"><%=t ".title" %></h1>

<%= link_to(image_tag("voltar-24.png", :title => "Voltar"), course_lesson_path(@lesson.course, @lesson), :class => "back-link") %><br /><br />

<%= render 'form', :lesson => @lesson, :activity => @activity %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Lesson</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.name %></td>
    <td><%= activity.description %></td>
    <td><%= activity.lesson %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p>
  <b>Name:</b>
  <%= @activity.name %>
</p>